### ISSUE TITLE
x-xlite pro

### ISSUE THREAD

**Issue by MartinSunal** [jfrickmann/SoarOTX#10]
hello,

how does it look with support of x-lite pro?
It uses opentx 2.3 and I am getting "syntax error" for SoarOTX scripts.

Thank you,
Martin

**Comment by jfrickmann** [comment]
When Companion 2.3 is out, I will take a look at it.

-----------------------
Jesper Frickmann
________________________________

**Comment by vitas** [comment]
it is out, 2.3.1

**Comment by jbruce12000** [comment]
I'm running 2.3.0 fine with my x-lite pro and I don't have any errors running the SoarOTX scripts.  Can you be more specific about the script you're running?

Here are the details of my xlite-pro software:

- firmware file: firmware_xlites_pro_190720.bin (downloaded from frsky)
- firmware version: OpenTX v2.3.0
- sdcard version: 2.3v0019
- companion version: 2.3.0

**Comment by jfrickmann** [comment]
To switch between telemetry screens on Xlite, press SHIFT + DOWN.
