### ISSUE TITLE
X-Lite Pro and F5J - possible?

### ISSUE THREAD

**Issue by BernhardGruen** [jfrickmann/SoarOTX#13]
Hello Jesper,

I just had a possible strange idea: would it be possible to use the X-Lite Pro to fly F5J contest models?

I just tested it in companion and imported the F5J model from the QX7 file into the X-Lite Pro file. At first sight there are not enough buttons available to manage all functions, but...
we have two momentary switches with the X-Lite Pro - ideally usable as arm switch (L05, L06) and motor enable switch (L08).
Then the 2 position switch SD (L07) could be used as data logging switch and the other 2 position switch SC (L09) could be used as altitude announcement switch.
The two pot switches (S1 and S2) would still be available for fine tuning.

I don't know - and I can't test it in real life just now - if this is feasible but it at least sounds possible to me.

What do you think (as the programmer of SoarOTX and as a F5J pilot)?

**Comment by BernhardGruen** [comment]
Ok, does not work in practice. You need to have an thrower all the time. Also the KAPOW mode comes into play sometimes.

**Comment by jfrickmann** [comment]
Yes, I found that it was difficult to map the J programs to the little radios, so I left it out.
