### ISSUE TITLE
xlite-pro

### ISSUE THREAD

**Issue by jbruce12000** [jfrickmann/SoarOTX#14]
Hi JF,

First, thx for all your hard work.  I have an xlite-pro and the I've copied all the lua scripts over to the sdcard.  when I enter the telemetry screen, there is a single menu called "plugins" which contains the following:

1. F3k
2. Practice
3. Altimeter
4. F3K 2020
5. Saved scores

but there is no 2nd page in Telemetry where I can select the configuration scripts as detailed in the wiki. I verified all the config scripts are on my sdcard...

/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/ADJMIX.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/ALIGN.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/CENTER.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/MENU.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/SK.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/SK1.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/SK2.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/SK3.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/SK4.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/SK9.lua
/media/jbruce/otx-sdcard/SCRIPTS/TELEMETRY/JF3K/SKalti.lua

Do I need to do something special to get to the menu containing these scripts?  You cannot execute them by browsing the SDCard and executing them.

Any help would be appreciated.

**Comment by jfrickmann** [comment]
To switch between telemetry screens on Xlite, press SHIFT + DOWN.

Jesper Frickmann

________________________________

**Comment by jbruce12000** [comment]
haha.  for anyone else that finds this...

To change telemetry screens on the xlite-pro

1. hold the button just to right of the thumb joystick down
2. push the thumb joystick to the left or right to move through the telemetry screens
