### ISSUE TITLE
support of Jumper T12

### ISSUE THREAD

**Issue by vitas** [jfrickmann/SoarOTX#17]
Would be great to make adjustments to run the program on Jumper T12
it is basically QX7 with different navigation. I used the program, old version with great success.
Looks like it cannot leave  the menu as there is no home button.

**Comment by vitas** [comment]
I changed the util script to react home as long right and it works as expected, maybe there is a better way to do that

-- Show or hide help text
function soarUtil.ToggleHelp(event)
	if soarUtil.showHelp then
		soarUtil.showHelp = (event ~= EVT_MENU_BREAK and event ~= EVT_SHIFT_BREAK and event ~= EVT_RIGHT_LONG)
	else
		soarUtil.showHelp = (event == EVT_MENU_BREAK or event == EVT_SHIFT_BREAK or event == EVT_RIGHT_LONG)
	end
end -- ToggleHelp()

**Comment by jfrickmann** [comment]
Heh, I didn't know that Jumpers were that similar. I have added support for T12, press LEFT+RIGHT down together to toggle help.

**Comment by vitas** [comment]
thank you, Jesper!
