### ISSUE TITLE
rudder trim on launch

### ISSUE THREAD

**Issue by fluxsaas** [jfrickmann/SoarOTX#2]
hi!

thanks a lot for your work! as a beginner, it helps a to get me started with F3K.

Quick question: i can see that the trim changes for the rudder on launch to "-3" on my taranis x7s display, where would i check to increase the trim? i would guess the trim is defined in the flight mode in an global variable?

best,
Kalle

**Comment by fluxsaas** [comment]
alright, i got it. 

it's simpler to use the companion app to see the trims: (sorry, its german)

<img width="855" alt="screenshot 2018-07-25 13 35 28" src="https://user-images.githubusercontent.com/13223/43198634-a52991d4-900f-11e8-8a47-9b1cfe952d9b.png">

if you want to change the trims without the app, you need to change the trim while you have activated the flight mode.

**Comment by jfrickmann** [comment]
Glad to hear that you figured it out :-)
