### ISSUE TITLE
XLite use left-ail-trim as momentary switch for launch?

### ISSUE THREAD

**Issue by CaleyD** [jfrickmann/SoarOTX#20]
I'm new to DLGs and currently fly with an xlite, I don't want to physically mod it but figured a momentary swirtch for launch mode would be helpful.

Do you have any ideas how I can best modify the F3K setup to use the left aileron trim as a momentary switch for launch purposes? 

I was considering either completely decomissioning the aileron trims in cruise and launch mode and updating the logical switch to use the left aileron trim to enable launch mode, or using the current launch mode switch as a custom "prelaunch mode" that has trims disabled and just serves to listen to the trim button to flip to the correct mode (after which the prelaunch mode is ignored until reset)... 

BTW - I've been flying for a few years and until stumbling on this repo had no idea what was really possible with OpenTX - this repo is very impressive!

**Comment by jfrickmann** [comment]
You can just assign the Launch LS to left aileron trim. Here is a table with logical switches, what they do, and their default assignments: https://github.com/jfrickmann/SoarOTX/wiki/2.-Model-configuration#switch-reassignment

As you mention, you have to find a way to disable the trim so you do not change it every time that you launch.
