### ISSUE TITLE
Altitude always announced in meters

### ISSUE THREAD

**Issue by dan-1d** [jfrickmann/SoarOTX#21]
I'm not sure if this is a bug in opentx, soarotx, or my configuration problem.

I can't get altitude calls annouced in feet. They are always in meters. I've changed the telemetry sensor units and radio settings to 'imperial'

This unit seems hardcoded in jfutil.lua
Was the variable
unitAlt = field.unit
 supposed to update 
soarUtil.altUnit
As used in
playNumber(soarUtil.alt, soarUtil.altUnit)

When I get some time I can try to fix this via a PR.. but it's here for reference.

Thanks so much for this software package! Love it.

**Comment by jfrickmann** [comment]
Your analysis is 100% correct. I have replaced unitAlt by soarUtil.altUnit, and tested that it works on my transmitter.
Thanks!
