### ISSUE TITLE
T16 support

### ISSUE THREAD

**Issue by arrowcircle** [jfrickmann/SoarOTX#22]
Hey! Thanks for the great work!

I used your scripts to fly dlg with my x9dplus, but now switched to Radiomaster T16s.
Any plans on adding support of Horus-like radios?

In the wiki you say something about interactive lua scripts, but whats that?

**Comment by jfrickmann** [comment]
Interactive means that you can interact with the script by pressing buttons or turning the rotary etc. This is not possible on Horus radios today. As an ex. you cannot press ENTER to select a task.

**Comment by arrowcircle** [comment]
Is it limited by Open TX? Is there any open issues or pull requests about that?

**Comment by jfrickmann** [comment]
Yes. Please see https://github.com/opentx/opentx/pull/6688.

**Comment by arrowcircle** [comment]
Is it possible to just use mixes and modes? If yes, should i just upload model to my radio (what model to use)?

**Comment by jfrickmann** [comment]
I think it is. If you decide to try it, please let me know how it works!

-----------------------
Jesper Frickmann
________________________________

**Comment by arrowcircle** [comment]
Here is the quick report.

I used x9d+ model as a model with OpenTX 2.3.9.
One things to notice here, there are no telemetry page available on these screens, so I was unable to set lua script on my telemetry screens. Here is example of iNav widget, that can be selected for telemetry screen https://github.com/iNavFlight/LuaTelemetry/blob/master/dist/WIDGETS/iNav/main.lua

Then I tried to execute JFUtil.lua, but got really informative  error message:

```lua
?:0
attempt to call a nil value
```

In terms of switches and mixes, everything works fine here.

I think modern version of OpenTX have tools folder in scripts to set up something. Should setup menu move here?

I can try to make it work, but dont know where to start from. Should I start on widget? Setup script? Or something else?

**Comment by jfrickmann** [comment]
Yes, the Horus-like transmitters use Lua widgets instead of Lua telemetry screens. And Lua widgets cannot read user inputs from keys and rotaries. That is why I am unable to make a version for Horus-like transmitters.

Jesper Frickmann

**Comment by arrowcircle** [comment]
Hi! It looks like Edge Tx 2.4.0 was recently released and I see SoarETX branch in this repo. 
I tried to add telemetry screens and execute scripts, but ring no bells.

Is there any help needed with testing?

**Comment by jfrickmann** [comment]
We are still working on the plumbing in EdgeTX, so it is not ready yet. The stuff under EdgeTX so far is only a small widget to test the event handling, and then a highly unfinished GUI library that I plan to use for implementing SoarETX. I will make an announcement when I have something to test. Hopefully within a few months!

**Comment by jfrickmann** [comment]
Here is a little video showing the progress with event handling in Lua widgets. It is slated for EdgeTX 2.4.1, and the LibGUI library is what I plan to use for future widgets in SoarETX programs.
https://youtu.be/QSl6AVRojjw

**Comment by arrowcircle** [comment]
Hey! It looks like a great progress in SoarETX. I played with SoarETX with my t16s, but configuration scripts are missing, so I cant setup my f3k model. Is there are any simple way to setup glider without GUI interface? Or maybe there are any ETA for configuration scripts?

Any way, thanks for your great work anyway!

**Comment by jfrickmann** [comment]
Hi Oleg,
If you already have a program setup on a Taranis-style transmitter, then you can transfer it over with Companion. The only modification that it needs, is to delete special function SF1 that runs the script JFutil.lua.
I will of course get around to creating configuration scripts as well - hopefully before the end of the year.

**Comment by arrowcircle** [comment]
@jfrickmann Unfortunately, I lost my model from x9d and can't use it :(
