### ISSUE TITLE
JF-LS.lua crashes on Xlite Pro

### ISSUE THREAD

**Issue by btreecat** [jfrickmann/SoarOTX#24]
When attempting to run the configuration script to set the right channel mapping and directions, my radio reboots. Subsequent runs just crash with the error message 

```
Script error: ...JF-LS.lua:162: attempt to perform arithmetic on upvalue 'LS_BASE' (a nil value)
```

I attempted to init the value to `0` if `nil` but this lead to another issue with `iLS` being `nil` elsewhere. 

I get the same error when I attempt to run the script in the simulator. 

This also causes my RX settings to get lost. 

* Radio: Xlite Pro
* Firmware: OpenTX 2.3.15
* SoarOTX: git main branch

**Comment by btreecat** [comment]
Added this else block to the init() function. Seems to stop crashing in the simulator. Going to test on my radio later. 

```lua
else -- Other
		tx = TX_UNKNOWN
		LS_BASE = 0
		switchNames = {
			"A\192", "A-", "A\193",
			"B\192", "B-", "B\193",
			"C\192", "C-", "C\193",
			"D\192", "D-", "D\193",
			"E\192", "E-", "E\193",
			"F\192", "F-", "F\193"
		}
```

**Comment by jfrickmann** [comment]
Most likely, I have to change 
`if string.find(radio, "x7") then`
to
`if string.find(radio, "x7") or string.find(radio, "xlite") then`
I will look into it tonight

**Comment by btreecat** [comment]
How can I determine the correct LS_BASE value for the xlite?

**Comment by jfrickmann** [comment]
You have to set up a model where L01 is used as source, and then you must read out the values with Lua. Same for FM_BASE. That's why there is no `else` clause in the `if` block (better crash the script than completely messing up the model's logical switches) and why I need to look at it carefully before making a fix!

**Comment by btreecat** [comment]
I should be able to work that out, do you already have a lua script that does this?

**Comment by jfrickmann** [comment]
No, and I am at work right now

**Comment by btreecat** [comment]
Looks like LS_BASE = (total_num_switch * 6) + 2 maybe?

I am not sure how I can set  L01 as a source, still trying to figure that
out.

--
Stephen Tanner
Senior Software Engineer
Citrine Informatics
Part 107 Certified Drone Pilot
TannAir LLC
https://TannAir.com
https://StephenTanner.com

**Comment by btreecat** [comment]
I Think FM_BASE = LS_BASE + (total_fm * 8) + 3

where `total_fm` is the total number of flight modes (8)

and `total_num_switch` is the total number of physical switches (6)

**Comment by btreecat** [comment]
Since we know the total number of switches as defined by the table of `switchNames`, we can use that to calculate `LS_BASE` and then `FM_BASE` it seems. Working on a PR to submit later if my testing works out OK.

**Comment by jfrickmann** [comment]
Wait, did you say that you want to configure the channel outputs? This is not the right script for that!

This is a little standalone script for moving logical switches around, please see https://www.rcgroups.com/forums/showthread.php?p=44414761&postcount=3397

If you want to configure channel outputs, then it happens in the 3rd telemetry screen, first pt in the Configure menu.

https://github.com/jfrickmann/SoarOTX/wiki/2.-Model-configuration#output-channel-configuration
