### ISSUE TITLE
mixing AIL into launch+zoom mode 

### ISSUE THREAD

**Issue by fluxsaas** [jfrickmann/SoarOTX#3]
hey!

some models need aileron reflex during launch and zoom mode to reduce drag:

![reflexed](https://user-images.githubusercontent.com/13223/43420898-7d1d1dac-9445-11e8-88fc-2c34aa96bbfe.gif)

vs:

![not_reflexed](https://user-images.githubusercontent.com/13223/43420917-8ab3bffc-9445-11e8-92f2-19366541b95d.gif)

would it make sense to implement this for F3K Model?

i would be happy to provide a pull request, if you could point me in the right direction.

**Comment by jfrickmann** [comment]
Please refer to the [Wiki for setting up a F3K model](https://github.com/jfrickmann/SoarOTX/wiki/F3K-Program#model-setup). "The third menu is for setting air brake and aileron travels. Use throttle trim to adjust the flaperons to the position of **maximum reflex**." You should set up the model with reflex here, and then add camber in various flight modes to get to other positions.

**Comment by fluxsaas** [comment]
ah, ok. so like my previous ticket, i have have to set my transmitter to the respective flight mode and then adjust the flaperons in the (3. center flaperons). 

i was certain all the "Model setup options" would only reflect the base flight mode. 

by the way, on my taranis q x7s, i cannot see the right side of the screen. the red rectangle is what is visible now:

![jf3kcenter](https://user-images.githubusercontent.com/13223/43441618-bdd9b5b6-949b-11e8-9a23-1f79fb5e9958.png)

**Comment by jfrickmann** [comment]
That's strange, this is what it looks like on Companion.

![screenshot_x7_18-07-31_07-08-33](https://user-images.githubusercontent.com/16344987/43456232-ae514c4a-9490-11e8-828b-dfe93e83edf5.png)

I added the variables to QX7 recently - do you have the latest version of the scripts?

**Comment by fluxsaas** [comment]
ah, i copied the QX7.otx file, but not the SD card content. i have upgraded everything and it runs smoothly now!

thanks a lot!
