### ISSUE TITLE
displays altitude even in FAI mode

### ISSUE THREAD

**Issue by MartinSunal** [jfrickmann/SoarOTX#7]
Hi Jesper,

I've flashed x9d+ to firmware 2.2.3 which includes FAI mode and it supposed to disable telemetry from vario but I still see altitude displaying on top bar.

I found this thread where FAI mode was fixed in opentx:
https://github.com/opentx/opentx/issues/3443
I see value 0 for Alti and Alt in the telemetry menu so I guess the fix in opentx works?

Could it be related to lua scripts?

Thank you,
Martin

**Comment by jfrickmann** [comment]
I am not familiar with the OpenTX issue, but from the description in your link, it appears to be a problem. You could simply disable the sensors that you do not want to see in your model setup. Obviously, the openTX team needs to fix it ASAP, so we can use Taranis radios at international contests.

Jesper

**Comment by jfrickmann** [comment]
Reading a little more of the thread, I tend to agree that under the current rules, you cannot carry an altimeter or other non-approved sensor in your plane, no matter what. I.e. the FAI mode would not be FAI compliant, even if it worked correctly.

**Comment by MartinSunal** [comment]
thanks for reply. I've created issue in opentx https://github.com/opentx/opentx/issues/6363
