### ISSUE TITLE
Graph from saved data

### ISSUE THREAD

**Issue by Pilot07** [jfrickmann/SoarOTX#8]
Helo J.,

after update to 2.2.3 CZ is there some problem with graph drawing from log. I think, that problem is with incorrect character (CZ language). Sample LOG file is attached.
Karel

[Maia-2019-04-06.zip](https://github.com/jfrickmann/SoarOTX/files/3058665/Maia-2019-04-06.zip)

**Comment by Pilot07** [comment]
This line working :-)
local FIRST_EXCLUDED = "Pln" -- CHECH log files
Script GRREAD

Thank

**Comment by jfrickmann** [comment]
Thanks,

I will update that in the file on GitHub.

-------------------
Jesper Frickmann

________________________________
