### ISSUE TITLE
Using soarotx with the Frsky X7S and 8DR-II rx. found a short issue.

### ISSUE THREAD

**Issue by JeffinSpringfield** [jfrickmann/SoarOTX#9]
I loaded the F3K program for a pike 6 channel plane.
used channel port 8 for the battery, 4.8 1300mah.
Plugged in only Channel 1 and rudder works.
added plugging in Channel 2 and elevator works and then bad things happen.
Channel 8 shorts the battery and the insulation cooks off the batter leads.

I am a senior RC flyer and need to resolve and understand.

**Comment by jfrickmann** [comment]
I am sorry to hear that, but I cannot help you with electrical issues. I suggest that you always disconnect the battery before plugging or unplugging servos and other connectors. It can also be helpful to find other aeromodelers in your area, especially if there is a club, and get help from them.
